# Generated by Django 4.0.3 on 2022-04-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_champion_date_enrolled_champion_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='date_enrolled',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='race',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='region',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='role',
        ),
    ]
