# Generated by Django 4.0.3 on 2022-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_champion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='imagePosition',
            field=models.TextField(default='50% 50%'),
        ),
    ]
