# Generated by Django 4.0.3 on 2022-04-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_champion_imageposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='release_date',
            field=models.TextField(default=''),
        ),
    ]
