# Generated by Django 4.0.3 on 2022-04-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_champion_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='imagePosition',
            field=models.CharField(default='50% 50%', max_length=50),
        ),
        migrations.AlterField(
            model_name='champion',
            name='release_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
